# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Service')),
            ],
        ),
    ]
